-- Identity-bound @mentions for review captions and comments. All existing
-- functions remain available so released 4.0.2 clients keep their current
-- write/read behavior while the mention-aware client moves to v2 contracts.

BEGIN;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS mention_notifications_enabled boolean
  NOT NULL DEFAULT true;

ALTER TABLE public.app_analytics_events
  DROP CONSTRAINT IF EXISTS app_analytics_events_event_name_check;
ALTER TABLE public.app_analytics_events
  ADD CONSTRAINT app_analytics_events_event_name_check CHECK (
    event_name IN (
      'login', 'create_account', 'shared_app', 'share_review',
      'share_location', 'new_review', 'edit_review', 'like_review',
      'like_comment', 'view_location', 'comment_on_review', 'follow_user',
      'view_profile', 'change_avatar', 'report', 'delete_review', 'logout',
      'activity_open', 'activity_notification_open', 'activity_follow_back',
      'activity_page_load', 'activity_load_error', 'visitor_preview_started',
      'membership_gate_opened', 'membership_gate_dismissed',
      'membership_auth_started', 'onboarding_completed',
      'auth_unexpected_sign_out', 'auth_session_missing_at_launch',
      'mention_suggestions_opened', 'mention_selected', 'mention_submitted'
    )
  );

CREATE TABLE IF NOT EXISTS public.review_mentions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id bigint NOT NULL REFERENCES public.reviews(id) ON DELETE CASCADE,
  mentioned_profile_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  username_snapshot text NOT NULL,
  start_offset integer NOT NULL CHECK (start_offset >= 0),
  token_length integer NOT NULL CHECK (token_length BETWEEN 2 AND 21),
  created_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (review_id, start_offset)
);

CREATE TABLE IF NOT EXISTS public.comment_mentions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id integer NOT NULL REFERENCES public.comments(id) ON DELETE CASCADE,
  mentioned_profile_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  username_snapshot text NOT NULL,
  start_offset integer NOT NULL CHECK (start_offset >= 0),
  token_length integer NOT NULL CHECK (token_length BETWEEN 2 AND 21),
  created_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (comment_id, start_offset)
);

-- This immutable ledger prevents remove/re-add edits from notifying the same
-- member more than once for one source. Notification rows may be withdrawn;
-- delivery history intentionally remains.
CREATE TABLE IF NOT EXISTS public.mention_delivery_ledger (
  source_kind text NOT NULL CHECK (source_kind IN ('review', 'comment')),
  source_id bigint NOT NULL,
  mentioned_profile_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  actor_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  notification_id uuid REFERENCES public.notifications(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (source_kind, source_id, mentioned_profile_id)
);

CREATE INDEX IF NOT EXISTS review_mentions_review_target_idx
  ON public.review_mentions (review_id, mentioned_profile_id);
CREATE INDEX IF NOT EXISTS comment_mentions_comment_target_idx
  ON public.comment_mentions (comment_id, mentioned_profile_id);
CREATE INDEX IF NOT EXISTS mention_delivery_recipient_idx
  ON public.mention_delivery_ledger (mentioned_profile_id, created_at DESC);
CREATE INDEX IF NOT EXISTS profiles_username_mentions_trgm_idx
  ON public.profiles USING gin ((lower(username)) gin_trgm_ops)
  WHERE deleted = false;

ALTER TABLE public.review_mentions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comment_mentions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mention_delivery_ledger ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.review_mentions FROM anon, authenticated;
REVOKE ALL ON TABLE public.comment_mentions FROM anon, authenticated;
REVOKE ALL ON TABLE public.mention_delivery_ledger FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.search_mention_candidates_v1(
  p_query text DEFAULT '',
  p_limit integer DEFAULT 5
) RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  WITH request AS (
    SELECT
      auth.uid() AS viewer_id,
      lower(trim(COALESCE(p_query, ''))) AS query,
      least(greatest(COALESCE(p_limit, 5), 1), 10) AS result_limit
  ), candidates AS (
    SELECT
      candidate.id,
      candidate.username,
      candidate.name,
      candidate.avatar_url,
      candidate.is_verified,
      candidate.review_count,
      viewer_follows.followed_at AS viewer_followed_at,
      follows_viewer.followed_at AS followed_viewer_at,
      recent.last_interaction_at,
      CASE
        WHEN viewer_follows.follower_id IS NOT NULL
         AND follows_viewer.follower_id IS NOT NULL THEN 0
        WHEN viewer_follows.follower_id IS NOT NULL THEN 1
        WHEN follows_viewer.follower_id IS NOT NULL THEN 2
        WHEN recent.last_interaction_at IS NOT NULL THEN 3
        ELSE 4
      END AS relationship_rank,
      CASE
        WHEN request.query = '' THEN 0
        WHEN lower(candidate.username) = request.query THEN 0
        WHEN lower(candidate.username) LIKE request.query || '%' THEN 1
        ELSE 2
      END AS match_rank
    FROM request
    JOIN public.profiles candidate
      ON request.viewer_id IS NOT NULL
     AND candidate.id <> request.viewer_id
     AND candidate.deleted = false
     AND NULLIF(trim(candidate.username), '') IS NOT NULL
    LEFT JOIN public.followers viewer_follows
      ON viewer_follows.follower_id = request.viewer_id
     AND viewer_follows.following_id = candidate.id
    LEFT JOIN public.followers follows_viewer
      ON follows_viewer.follower_id = candidate.id
     AND follows_viewer.following_id = request.viewer_id
    LEFT JOIN LATERAL (
      SELECT max(interaction_at) AS last_interaction_at
      FROM (
        SELECT c.inserted_at AS interaction_at
        FROM public.comments c
        JOIN public.reviews r ON r.id = c.review_id
        WHERE (c.user_id = candidate.id AND r.user_id = request.viewer_id)
           OR (c.user_id = request.viewer_id AND r.user_id = candidate.id)
        ORDER BY c.inserted_at DESC
        LIMIT 1
      ) interactions
    ) recent ON true
    WHERE NOT EXISTS (
      SELECT 1 FROM public.blocks block
      WHERE (block.blocker_id = request.viewer_id AND block.blocked_id = candidate.id)
         OR (block.blocker_id = candidate.id AND block.blocked_id = request.viewer_id)
    )
      AND (
        request.query = ''
        OR lower(candidate.username) LIKE '%' || request.query || '%'
        OR lower(COALESCE(candidate.name, '')) LIKE '%' || request.query || '%'
      )
  )
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'id', ranked.id,
    'username', ranked.username,
    'name', ranked.name,
    'avatarUrl', ranked.avatar_url,
    'isVerified', COALESCE(ranked.is_verified, false),
    'reviewCount', COALESCE(ranked.review_count, 0),
    'relationship', CASE ranked.relationship_rank
      WHEN 0 THEN 'mutual'
      WHEN 1 THEN 'following'
      WHEN 2 THEN 'follows_you'
      WHEN 3 THEN 'recent'
      ELSE 'everyone'
    END
  ) ORDER BY
    ranked.relationship_rank,
    ranked.match_rank,
    ranked.last_interaction_at DESC NULLS LAST,
    lower(ranked.username),
    ranked.id), '[]'::jsonb)
  FROM (
    SELECT candidates.*
    FROM candidates, request
    ORDER BY
      relationship_rank,
      match_rank,
      last_interaction_at DESC NULLS LAST,
      lower(username),
      id
    LIMIT (SELECT result_limit FROM request)
  ) ranked;
$$;

REVOKE ALL ON FUNCTION public.search_mention_candidates_v1(text, integer)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.search_mention_candidates_v1(text, integer)
  TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.mention_target_is_eligible(
  p_actor_id uuid,
  p_target_id uuid
) RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT p_actor_id IS NOT NULL
    AND p_target_id IS NOT NULL
    AND p_actor_id <> p_target_id
    AND EXISTS (
      SELECT 1 FROM public.profiles target
      WHERE target.id = p_target_id AND target.deleted = false
    )
    AND NOT public.push_users_are_blocked(p_actor_id, p_target_id);
$$;

REVOKE ALL ON FUNCTION public.mention_target_is_eligible(uuid, uuid)
  FROM PUBLIC, anon, authenticated;

-- React Native selection offsets use JavaScript UTF-16 code units. Postgres
-- string positions use Unicode code points, so validate client offsets with a
-- small converter instead of accepting a matching token elsewhere in the
-- body. Usernames are ASCII, making token length identical in both systems.
CREATE OR REPLACE FUNCTION public.mention_token_matches_utf16(
  p_body text,
  p_start_offset integer,
  p_token text,
  p_token_length integer
) RETURNS boolean
LANGUAGE plpgsql
IMMUTABLE
STRICT
SET search_path = public, pg_temp
AS $$
DECLARE
  v_character text;
  v_character_index integer := 1;
  v_code_unit_offset integer := 0;
BEGIN
  IF p_start_offset < 0
     OR p_token_length <> char_length(p_token)
     OR p_token_length < 2 THEN
    RETURN false;
  END IF;

  WHILE v_character_index <= char_length(p_body)
        AND v_code_unit_offset < p_start_offset LOOP
    v_character := substring(p_body FROM v_character_index FOR 1);
    v_code_unit_offset := v_code_unit_offset + CASE
      WHEN octet_length(convert_to(v_character, 'UTF8')) = 4 THEN 2
      ELSE 1
    END;
    v_character_index := v_character_index + 1;
  END LOOP;

  -- The token must also end at a word boundary: '@bobs' is not a mention of
  -- '@bob', so a trailing username character rejects the span.
  RETURN v_code_unit_offset = p_start_offset
    AND substring(
      p_body FROM v_character_index FOR char_length(p_token)
    ) = p_token
    AND COALESCE(
      substring(p_body FROM v_character_index + char_length(p_token) FOR 1),
      ''
    ) !~ '^[A-Za-z0-9_]$';
END;
$$;

REVOKE ALL ON FUNCTION public.mention_token_matches_utf16(
  text, integer, text, integer
) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.enqueue_mention_once(
  p_source_kind text,
  p_source_id bigint,
  p_actor_id uuid,
  p_target_id uuid,
  p_review_id bigint,
  p_comment_id integer DEFAULT NULL
) RETURNS void
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_actor_name text;
  v_kind text;
  v_notification_id uuid;
  v_preference boolean;
BEGIN
  IF p_source_kind NOT IN ('review', 'comment')
     OR NOT public.mention_target_is_eligible(p_actor_id, p_target_id) THEN
    RETURN;
  END IF;

  -- Check the preference before writing delivery history: a ledger row for a
  -- muted mention would permanently block delivery after the member re-enables
  -- mention notifications.
  SELECT target.mention_notifications_enabled
  INTO v_preference
  FROM public.profiles target
  WHERE target.id = p_target_id;

  IF NOT COALESCE(v_preference, true) THEN RETURN; END IF;

  INSERT INTO public.mention_delivery_ledger (
    source_kind, source_id, mentioned_profile_id, actor_id
  ) VALUES (
    p_source_kind, p_source_id, p_target_id, p_actor_id
  ) ON CONFLICT DO NOTHING;

  IF NOT FOUND THEN
    -- Already delivered once. If a caption edit withdrew that notification,
    -- restore it instead of leaving the re-added mention invisible forever.
    DELETE FROM public.activity_withdrawals withdrawal
    USING public.notifications notification
    WHERE withdrawal.notification_id = notification.id
      AND withdrawal.reason = 'action_undone'
      AND notification.event_key = concat(
        'mention:', p_source_kind, ':', p_source_id, ':', p_target_id
      );
    RETURN;
  END IF;

  SELECT COALESCE(actor.username, 'Someone')
  INTO v_actor_name
  FROM public.profiles actor
  WHERE actor.id = p_actor_id;

  v_kind := CASE p_source_kind
    WHEN 'review' THEN 'mentioned_in_review'
    ELSE 'mentioned_in_comment'
  END;

  INSERT INTO public.notifications (
    user_id, actor_id, body, type, kind, data, event_key
  ) VALUES (
    p_target_id,
    p_actor_id,
    concat(
      v_actor_name,
      CASE p_source_kind
        WHEN 'review' THEN ' mentioned you in a review.'
        ELSE ' mentioned you in a comment.'
      END
    ),
    2,
    v_kind,
    jsonb_build_object(
      'kind', v_kind,
      'reviewId', p_review_id,
      'commentId', p_comment_id,
      'url', concat(
        '/r/', p_review_id,
        CASE WHEN p_comment_id IS NULL THEN ''
          ELSE concat('?comments=1&comment=', p_comment_id) END
      )
    ),
    concat('mention:', p_source_kind, ':', p_source_id, ':', p_target_id)
  ) ON CONFLICT (event_key) WHERE event_key IS NOT NULL DO NOTHING
  RETURNING id INTO v_notification_id;

  UPDATE public.mention_delivery_ledger
  SET notification_id = v_notification_id
  WHERE source_kind = p_source_kind
    AND source_id = p_source_id
    AND mentioned_profile_id = p_target_id;
END;
$$;

REVOKE ALL ON FUNCTION public.enqueue_mention_once(
  text, bigint, uuid, uuid, bigint, integer
) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.replace_review_mentions_v1(
  p_review_id bigint,
  p_body text,
  p_mentions jsonb DEFAULT '[]'::jsonb
) RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_actor_id uuid := auth.uid();
  v_item record;
  v_old_targets uuid[];
  v_result jsonb := '[]'::jsonb;
  v_target_id uuid;
  v_target_ids uuid[] := ARRAY[]::uuid[];
BEGIN
  IF v_actor_id IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.reviews r
    WHERE r.id = p_review_id AND r.user_id = v_actor_id
  ) THEN
    RAISE EXCEPTION 'The review is unavailable' USING ERRCODE = '42501';
  END IF;
  IF char_length(COALESCE(p_body, '')) > 500 THEN
    RAISE EXCEPTION 'Review captions are limited to 500 characters'
      USING ERRCODE = '22023';
  END IF;
  IF jsonb_typeof(COALESCE(p_mentions, '[]'::jsonb)) <> 'array'
     OR jsonb_array_length(COALESCE(p_mentions, '[]'::jsonb)) > 25 THEN
    RAISE EXCEPTION 'Mention payload is invalid' USING ERRCODE = '22023';
  END IF;

  SELECT COALESCE(array_agg(DISTINCT mentioned_profile_id)
    FILTER (WHERE mentioned_profile_id IS NOT NULL), ARRAY[]::uuid[])
  INTO v_old_targets
  FROM public.review_mentions
  WHERE review_id = p_review_id;

  DELETE FROM public.review_mentions WHERE review_id = p_review_id;

  FOR v_item IN
    SELECT * FROM jsonb_to_recordset(COALESCE(p_mentions, '[]'::jsonb))
      AS item(profile_id text, username text, start integer, length integer)
    ORDER BY start
  LOOP
    SELECT target.id INTO v_target_id
    FROM public.profiles target
    WHERE target.id::text = v_item.profile_id
      AND public.mention_target_is_eligible(v_actor_id, target.id)
      AND lower(target.username) = lower(v_item.username)
      AND v_item.username ~ '^[A-Za-z0-9_]{3,20}$'
      AND v_item.length = char_length(v_item.username) + 1
      AND public.mention_token_matches_utf16(
        p_body, v_item.start, '@' || v_item.username, v_item.length
      );

    IF v_target_id IS NULL THEN CONTINUE; END IF;
    IF NOT v_target_id = ANY(v_target_ids) THEN
      IF cardinality(v_target_ids) >= 5 THEN CONTINUE; END IF;
      v_target_ids := array_append(v_target_ids, v_target_id);
    END IF;

    BEGIN
      INSERT INTO public.review_mentions (
        review_id, mentioned_profile_id, username_snapshot,
        start_offset, token_length, created_by
      ) VALUES (
        p_review_id, v_target_id, v_item.username,
        v_item.start, v_item.length, v_actor_id
      );
      v_result := v_result || jsonb_build_array(jsonb_build_object(
        'profileId', v_target_id,
        'username', v_item.username,
        'start', v_item.start,
        'length', v_item.length
      ));
    EXCEPTION WHEN unique_violation OR check_violation THEN
      CONTINUE;
    END;
  END LOOP;

  FOREACH v_target_id IN ARRAY v_target_ids LOOP
    PERFORM public.enqueue_mention_once(
      'review', p_review_id, v_actor_id, v_target_id, p_review_id, NULL
    );
  END LOOP;

  FOREACH v_target_id IN ARRAY v_old_targets LOOP
    IF NOT v_target_id = ANY(v_target_ids) THEN
      INSERT INTO public.activity_withdrawals (notification_id, user_id, reason)
      SELECT notification.id, notification.user_id, 'action_undone'
      FROM public.notifications notification
      WHERE notification.event_key = concat(
        'mention:review:', p_review_id, ':', v_target_id
      )
      ON CONFLICT (notification_id) DO UPDATE
      SET reason = EXCLUDED.reason, withdrawn_at = now();
    END IF;
  END LOOP;

  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.replace_review_mentions_v1(bigint, text, jsonb)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.replace_review_mentions_v1(bigint, text, jsonb)
  TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.replace_comment_mentions_v1(
  p_comment_id integer,
  p_body text,
  p_mentions jsonb DEFAULT '[]'::jsonb
) RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_actor_id uuid := auth.uid();
  v_item record;
  v_result jsonb := '[]'::jsonb;
  v_review_id bigint;
  v_target_id uuid;
  v_target_ids uuid[] := ARRAY[]::uuid[];
BEGIN
  SELECT comment.review_id
  INTO v_review_id
  FROM public.comments comment
  WHERE comment.id = p_comment_id AND comment.user_id = v_actor_id;

  IF v_actor_id IS NULL OR v_review_id IS NULL THEN
    RAISE EXCEPTION 'The comment is unavailable' USING ERRCODE = '42501';
  END IF;
  IF char_length(COALESCE(p_body, '')) > 500 THEN
    RAISE EXCEPTION 'Comments are limited to 500 characters'
      USING ERRCODE = '22023';
  END IF;
  IF jsonb_typeof(COALESCE(p_mentions, '[]'::jsonb)) <> 'array'
     OR jsonb_array_length(COALESCE(p_mentions, '[]'::jsonb)) > 25 THEN
    RAISE EXCEPTION 'Mention payload is invalid' USING ERRCODE = '22023';
  END IF;

  DELETE FROM public.comment_mentions WHERE comment_id = p_comment_id;

  FOR v_item IN
    SELECT * FROM jsonb_to_recordset(COALESCE(p_mentions, '[]'::jsonb))
      AS item(profile_id text, username text, start integer, length integer)
    ORDER BY start
  LOOP
    SELECT target.id INTO v_target_id
    FROM public.profiles target
    WHERE target.id::text = v_item.profile_id
      AND public.mention_target_is_eligible(v_actor_id, target.id)
      AND lower(target.username) = lower(v_item.username)
      AND v_item.username ~ '^[A-Za-z0-9_]{3,20}$'
      AND v_item.length = char_length(v_item.username) + 1
      AND public.mention_token_matches_utf16(
        p_body, v_item.start, '@' || v_item.username, v_item.length
      );

    IF v_target_id IS NULL THEN CONTINUE; END IF;
    IF NOT v_target_id = ANY(v_target_ids) THEN
      IF cardinality(v_target_ids) >= 5 THEN CONTINUE; END IF;
      v_target_ids := array_append(v_target_ids, v_target_id);
    END IF;

    BEGIN
      INSERT INTO public.comment_mentions (
        comment_id, mentioned_profile_id, username_snapshot,
        start_offset, token_length, created_by
      ) VALUES (
        p_comment_id, v_target_id, v_item.username,
        v_item.start, v_item.length, v_actor_id
      );
      v_result := v_result || jsonb_build_array(jsonb_build_object(
        'profileId', v_target_id,
        'username', v_item.username,
        'start', v_item.start,
        'length', v_item.length
      ));
    EXCEPTION WHEN unique_violation OR check_violation THEN
      CONTINUE;
    END;
  END LOOP;

  FOREACH v_target_id IN ARRAY v_target_ids LOOP
    PERFORM public.enqueue_mention_once(
      'comment', p_comment_id, v_actor_id, v_target_id,
      v_review_id, p_comment_id
    );
  END LOOP;

  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.replace_comment_mentions_v1(integer, text, jsonb)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.replace_comment_mentions_v1(integer, text, jsonb)
  TO authenticated, service_role;

-- Released direct comment inserts still use their trigger. The v2 RPC sets
-- this transaction-local flag so it can collapse owner+mention collisions.
CREATE OR REPLACE FUNCTION public.enqueue_comment_notification()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_owner_id uuid;
  v_actor_name text;
  v_location_id bigint;
  v_location_name text;
BEGIN
  IF current_setting('ttc.suppress_comment_notification', true) = 'true' THEN
    RETURN NEW;
  END IF;

  SELECT r.user_id, r.location, l.name
  INTO v_owner_id, v_location_id, v_location_name
  FROM public.reviews r
  LEFT JOIN public.locations l ON l.id = r.location
  WHERE r.id = NEW.review_id;

  IF v_owner_id IS NULL OR v_owner_id = NEW.user_id OR
     public.push_users_are_blocked(NEW.user_id, v_owner_id) THEN
    RETURN NEW;
  END IF;

  SELECT COALESCE(username, 'Someone') INTO v_actor_name
  FROM public.profiles WHERE id = NEW.user_id;

  INSERT INTO public.notifications (
    user_id, actor_id, body, type, kind, data, event_key
  ) VALUES (
    v_owner_id,
    NEW.user_id,
    concat(
      v_actor_name,
      ' commented on your review from ',
      COALESCE(v_location_name, 'an unknown location')
    ),
    2,
    'review_commented',
    jsonb_build_object(
      'kind', 'review_commented',
      'reviewId', NEW.review_id,
      'commentId', NEW.id,
      'url', CASE WHEN v_location_id IS NULL THEN '/home'
        ELSE concat('/places/', v_location_id) END
    ),
    concat('comment:', NEW.id)
  ) ON CONFLICT (event_key) WHERE event_key IS NOT NULL DO NOTHING;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_comment_v2(
  p_review_id bigint,
  p_body text,
  p_mentions jsonb DEFAULT '[]'::jsonb
) RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_actor_id uuid := auth.uid();
  v_comment public.comments;
  v_mentions jsonb;
  v_owner_id uuid;
  v_actor_name text;
BEGIN
  IF v_actor_id IS NULL THEN
    RAISE EXCEPTION 'Authentication is required' USING ERRCODE = '42501';
  END IF;
  IF NULLIF(trim(p_body), '') IS NULL OR char_length(trim(p_body)) > 500 THEN
    RAISE EXCEPTION 'Comments must contain 1 to 500 characters'
      USING ERRCODE = '22023';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.reviews review
    JOIN public.profiles author ON author.id = review.user_id
    WHERE review.id = p_review_id AND review.state = 1
      AND author.deleted = false
      AND NOT public.push_users_are_blocked(v_actor_id, review.user_id)
  ) THEN
    RAISE EXCEPTION 'The review is unavailable' USING ERRCODE = '42501';
  END IF;

  PERFORM set_config('ttc.suppress_comment_notification', 'true', true);
  INSERT INTO public.comments (user_id, review_id, body)
  VALUES (v_actor_id, p_review_id, trim(p_body))
  RETURNING * INTO v_comment;

  v_mentions := public.replace_comment_mentions_v1(
    v_comment.id, v_comment.body, p_mentions
  );

  SELECT review.user_id INTO v_owner_id
  FROM public.reviews review WHERE review.id = p_review_id;

  IF v_owner_id IS NOT NULL
     AND v_owner_id <> v_actor_id
     AND NOT public.push_users_are_blocked(v_actor_id, v_owner_id)
     AND NOT EXISTS (
       SELECT 1 FROM public.comment_mentions mention
       WHERE mention.comment_id = v_comment.id
         AND mention.mentioned_profile_id = v_owner_id
     ) THEN
    SELECT COALESCE(username, 'Someone') INTO v_actor_name
    FROM public.profiles WHERE id = v_actor_id;
    INSERT INTO public.notifications (
      user_id, actor_id, body, type, kind, data, event_key
    ) VALUES (
      v_owner_id, v_actor_id,
      concat(v_actor_name, ' commented on your review.'),
      2, 'review_commented',
      jsonb_build_object(
        'kind', 'review_commented', 'reviewId', p_review_id,
        'commentId', v_comment.id,
        'url', concat('/r/', p_review_id, '?comments=1')
      ),
      concat('comment:', v_comment.id)
    ) ON CONFLICT (event_key) WHERE event_key IS NOT NULL DO NOTHING;
  END IF;

  RETURN to_jsonb(v_comment) || jsonb_build_object(
    'profile', (
      SELECT jsonb_build_object(
        'id', profile.id,
        'username', profile.username,
        'avatar_url', profile.avatar_url,
        'is_verified', profile.is_verified,
        'review_count', profile.review_count
      ) FROM public.profiles profile WHERE profile.id = v_actor_id
    ),
    'likes_count', 0,
    'has_liked', false,
    'mentions', v_mentions
  );
END;
$$;

REVOKE ALL ON FUNCTION public.create_comment_v2(bigint, text, jsonb)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_comment_v2(bigint, text, jsonb)
  TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.publish_review_v2(
  p_image_url text,
  p_location_id bigint DEFAULT NULL,
  p_location_name text DEFAULT NULL,
  p_location_address text DEFAULT NULL,
  p_place_id text DEFAULT NULL,
  p_latitude double precision DEFAULT NULL,
  p_longitude double precision DEFAULT NULL,
  p_spirit_id bigint DEFAULT NULL,
  p_type_id bigint DEFAULT NULL,
  p_taste numeric DEFAULT NULL,
  p_presentation numeric DEFAULT NULL,
  p_comment text DEFAULT '',
  p_mentions jsonb DEFAULT '[]'::jsonb
) RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY INVOKER
SET search_path = public, gis, pg_temp
AS $$
DECLARE
  v_result jsonb;
  v_review_id bigint;
BEGIN
  IF char_length(COALESCE(p_comment, '')) > 500 THEN
    RAISE EXCEPTION 'Review captions are limited to 500 characters'
      USING ERRCODE = '22023';
  END IF;
  v_result := public.publish_review_v1(
    p_image_url, p_location_id, p_location_name, p_location_address,
    p_place_id, p_latitude, p_longitude, p_spirit_id, p_type_id,
    p_taste, p_presentation, p_comment
  );
  v_review_id := (v_result->>'reviewId')::bigint;
  PERFORM public.replace_review_mentions_v1(
    v_review_id, trim(COALESCE(p_comment, '')), p_mentions
  );
  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.publish_review_v2(
  text, bigint, text, text, text, double precision, double precision,
  bigint, bigint, numeric, numeric, text, jsonb
) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.publish_review_v2(
  text, bigint, text, text, text, double precision, double precision,
  bigint, bigint, numeric, numeric, text, jsonb
) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.update_review_v2(
  p_review_id bigint,
  p_image_url text,
  p_location_id bigint,
  p_spirit_id bigint,
  p_type_id bigint,
  p_taste numeric,
  p_presentation numeric,
  p_comment text,
  p_mentions jsonb DEFAULT '[]'::jsonb
) RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_actor_id uuid := auth.uid();
  v_review public.reviews;
  v_mentions jsonb;
BEGIN
  IF v_actor_id IS NULL OR char_length(COALESCE(p_comment, '')) > 500 THEN
    RAISE EXCEPTION 'The review update is invalid' USING ERRCODE = '22023';
  END IF;
  UPDATE public.reviews review
  SET image_url = p_image_url,
      location = p_location_id,
      spirit = p_spirit_id,
      type = p_type_id,
      taste = p_taste,
      presentation = p_presentation,
      comment = trim(COALESCE(p_comment, ''))
  WHERE review.id = p_review_id AND review.user_id = v_actor_id
  RETURNING * INTO v_review;

  IF v_review.id IS NULL THEN
    RAISE EXCEPTION 'The review is unavailable' USING ERRCODE = '42501';
  END IF;
  IF p_mentions IS NULL THEN
    -- The client could not load the existing spans; leave them untouched
    -- rather than treating the edit as a request to remove every mention.
    SELECT COALESCE(jsonb_agg(jsonb_build_object(
      'profileId', mention.mentioned_profile_id,
      'username', mention.username_snapshot,
      'start', mention.start_offset,
      'length', mention.token_length
    ) ORDER BY mention.start_offset), '[]'::jsonb)
    INTO v_mentions
    FROM public.review_mentions mention
    WHERE mention.review_id = v_review.id;
  ELSE
    v_mentions := public.replace_review_mentions_v1(
      v_review.id, v_review.comment, p_mentions
    );
  END IF;
  RETURN to_jsonb(v_review) || jsonb_build_object('mentions', v_mentions);
END;
$$;

REVOKE ALL ON FUNCTION public.update_review_v2(
  bigint, text, bigint, bigint, bigint, numeric, numeric, text, jsonb
) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.update_review_v2(
  bigint, text, bigint, bigint, bigint, numeric, numeric, text, jsonb
) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.get_mention_spans_v1(
  p_review_ids bigint[] DEFAULT ARRAY[]::bigint[],
  p_comment_ids integer[] DEFAULT ARRAY[]::integer[]
) RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH request AS (SELECT auth.uid() AS viewer_id), mention_rows AS (
    SELECT
      'review'::text AS source_kind,
      mention.review_id::bigint AS source_id,
      mention.mentioned_profile_id AS profile_id,
      mention.username_snapshot AS username,
      mention.start_offset AS start,
      mention.token_length AS length
    FROM public.review_mentions mention
    JOIN public.reviews review ON review.id = mention.review_id AND review.state = 1
    JOIN public.profiles author ON author.id = review.user_id AND author.deleted = false
    CROSS JOIN request
    WHERE mention.review_id = ANY(COALESCE(p_review_ids, ARRAY[]::bigint[]))
      AND request.viewer_id IS NOT NULL
      AND mention.mentioned_profile_id IS NOT NULL
      AND NOT public.push_users_are_blocked(request.viewer_id, review.user_id)
      AND NOT public.push_users_are_blocked(request.viewer_id, mention.mentioned_profile_id)
    UNION ALL
    SELECT
      'comment'::text,
      mention.comment_id::bigint,
      mention.mentioned_profile_id,
      mention.username_snapshot,
      mention.start_offset,
      mention.token_length
    FROM public.comment_mentions mention
    JOIN public.comments comment ON comment.id = mention.comment_id
    JOIN public.reviews review ON review.id = comment.review_id AND review.state = 1
    JOIN public.profiles author ON author.id = comment.user_id AND author.deleted = false
    CROSS JOIN request
    WHERE mention.comment_id = ANY(COALESCE(p_comment_ids, ARRAY[]::integer[]))
      AND request.viewer_id IS NOT NULL
      AND mention.mentioned_profile_id IS NOT NULL
      AND NOT public.push_users_are_blocked(request.viewer_id, comment.user_id)
      AND NOT public.push_users_are_blocked(request.viewer_id, mention.mentioned_profile_id)
  )
  SELECT jsonb_build_object('mentions', COALESCE(jsonb_agg(jsonb_build_object(
    'sourceKind', source_kind,
    'sourceId', source_id,
    'profileId', profile_id,
    'username', username,
    'start', start,
    'length', length
  ) ORDER BY source_kind, source_id, start), '[]'::jsonb))
  FROM mention_rows;
$$;

REVOKE ALL ON FUNCTION public.get_mention_spans_v1(bigint[], integer[])
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_mention_spans_v1(bigint[], integer[])
  TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.activity_supported_notification(p_kind text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT p_kind IN (
    'user_followed', 'review_liked', 'comment_liked',
    'review_commented', 'comment_replied',
    'mentioned_in_review', 'mentioned_in_comment', 'admin_message'
  );
$$;

CREATE OR REPLACE FUNCTION public.get_activity_page(
  p_cursor_created_at timestamptz DEFAULT NULL,
  p_cursor_id uuid DEFAULT NULL,
  p_limit integer DEFAULT 30
) RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_limit integer := LEAST(GREATEST(COALESCE(p_limit, 30), 1), 50);
  v_snapshot_at timestamptz := now();
  v_result jsonb;
BEGIN
  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object(
      'events', '[]'::jsonb,
      'nextCursor', NULL,
      'hasMore', false,
      'snapshotAt', v_snapshot_at
    );
  END IF;

  WITH eligible AS (
    SELECT
      n.id,
      n.created_at,
      n.kind,
      n.body,
      n.actor_id,
      n.data,
      p.username AS actor_username,
      p.avatar_url AS actor_avatar_url,
      p.is_verified AS actor_is_verified,
      p.review_count AS actor_review_count,
      EXISTS (
        SELECT 1 FROM public.followers f
        WHERE f.follower_id = v_user_id AND f.following_id = n.actor_id
      ) AS is_following,
      r.id AS review_id,
      r.image_url AS review_image_path,
      r.location AS review_location_id,
      c.body AS comment_body,
      c.id AS comment_id,
      ar.seen_at,
      ar.read_at
    FROM public.notifications n
    LEFT JOIN public.profiles p ON p.id = n.actor_id
    LEFT JOIN public.reviews r ON r.id = CASE
      WHEN n.data->>'reviewId' ~ '^[0-9]+$'
        THEN (n.data->>'reviewId')::bigint ELSE NULL END
    LEFT JOIN public.comments c ON c.id = CASE
      WHEN n.data->>'commentId' ~ '^[0-9]+$'
        THEN (n.data->>'commentId')::integer ELSE NULL END
    LEFT JOIN public.activity_receipts ar
      ON ar.notification_id = n.id AND ar.user_id = v_user_id
    WHERE n.user_id = v_user_id
      AND n.type = 2
      AND public.activity_supported_notification(n.kind)
      AND n.created_at >= now() - interval '1 year'
      AND (n.kind = 'admin_message' OR n.actor_id IS NOT NULL)
      AND (p.id IS NULL OR p.deleted = false)
      AND NOT EXISTS (
        SELECT 1 FROM public.activity_withdrawals aw
        WHERE aw.notification_id = n.id
      )
      AND NOT EXISTS (
        SELECT 1 FROM public.blocks b
        WHERE n.actor_id IS NOT NULL
          AND ((b.blocker_id = v_user_id AND b.blocked_id = n.actor_id)
            OR (b.blocker_id = n.actor_id AND b.blocked_id = v_user_id))
      )
      AND (
        n.kind = 'admin_message'
        OR (
          r.id IS NOT NULL AND r.state = 1
          AND (
            n.kind IN ('review_liked', 'mentioned_in_review')
            OR c.id IS NOT NULL
          )
        )
      )
      AND (
        p_cursor_created_at IS NULL
        OR n.created_at < p_cursor_created_at
        OR (n.created_at = p_cursor_created_at AND n.id < p_cursor_id)
      )
    ORDER BY n.created_at DESC, n.id DESC
    LIMIT v_limit + 1
  ), page AS (
    SELECT * FROM eligible ORDER BY created_at DESC, id DESC LIMIT v_limit
  ), payload AS (
    SELECT COALESCE(jsonb_agg(jsonb_build_object(
      'id', id,
      'createdAt', created_at,
      'kind', kind,
      'body', body,
      'actor', CASE WHEN actor_id IS NULL THEN NULL ELSE jsonb_build_object(
        'id', actor_id,
        'username', actor_username,
        'avatarUrl', actor_avatar_url,
        'isVerified', COALESCE(actor_is_verified, false),
        'reviewCount', COALESCE(actor_review_count, 0)
      ) END,
      'isFollowing', COALESCE(is_following, false),
      'review', CASE WHEN review_id IS NULL THEN NULL ELSE jsonb_build_object(
        'id', review_id,
        'imagePath', review_image_path,
        'locationId', review_location_id
      ) END,
      'comment', CASE WHEN comment_id IS NULL THEN NULL ELSE jsonb_build_object(
        'id', comment_id,
        'body', comment_body
      ) END,
      'data', COALESCE(data, '{}'::jsonb),
      'seenAt', seen_at,
      'readAt', read_at
    ) ORDER BY created_at DESC, id DESC), '[]'::jsonb) AS events
    FROM page
  ), meta AS (
    SELECT count(*) > v_limit AS has_more FROM eligible
  ), cursor_row AS (
    SELECT created_at, id FROM eligible
    ORDER BY created_at DESC, id DESC
    OFFSET v_limit - 1 LIMIT 1
  )
  SELECT jsonb_build_object(
    'events', payload.events,
    'hasMore', meta.has_more,
    'snapshotAt', v_snapshot_at,
    'nextCursor', CASE WHEN meta.has_more THEN jsonb_build_object(
      'createdAt', cursor_row.created_at,
      'id', cursor_row.id
    ) ELSE NULL END
  ) INTO v_result
  FROM payload, meta LEFT JOIN cursor_row ON true;

  RETURN v_result;
END;
$$;

-- Existing withdrawal helpers must treat mentions like their source content.
CREATE OR REPLACE FUNCTION public.withdraw_comment_activity()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO public.activity_withdrawals (notification_id, user_id, reason)
  SELECT n.id, n.user_id, 'source_deleted'
  FROM public.notifications n
  WHERE n.kind IN (
    'review_commented', 'comment_replied', 'comment_liked',
    'mentioned_in_comment'
  ) AND n.data->>'commentId' = OLD.id::text
  ON CONFLICT (notification_id) DO UPDATE
  SET reason = EXCLUDED.reason, withdrawn_at = now();
  RETURN OLD;
END;
$$;

CREATE OR REPLACE FUNCTION public.withdraw_review_activity()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NEW.state IS DISTINCT FROM OLD.state AND NEW.state IS DISTINCT FROM 1 THEN
    INSERT INTO public.activity_withdrawals (notification_id, user_id, reason)
    SELECT n.id, n.user_id, 'source_deleted'
    FROM public.notifications n
    WHERE n.kind IN (
      'review_liked', 'comment_liked', 'review_commented', 'comment_replied',
      'mentioned_in_review', 'mentioned_in_comment'
    ) AND n.data->>'reviewId' = NEW.id::text
    ON CONFLICT (notification_id) DO UPDATE
    SET reason = EXCLUDED.reason, withdrawn_at = now();
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.withdraw_deleted_review_activity()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO public.activity_withdrawals (notification_id, user_id, reason)
  SELECT n.id, n.user_id, 'source_deleted'
  FROM public.notifications n
  WHERE n.kind IN (
    'review_liked', 'comment_liked', 'review_commented', 'comment_replied',
    'mentioned_in_review', 'mentioned_in_comment'
  ) AND n.data->>'reviewId' = OLD.id::text
  ON CONFLICT (notification_id) DO UPDATE
  SET reason = EXCLUDED.reason, withdrawn_at = now();
  RETURN OLD;
END;
$$;

CREATE OR REPLACE FUNCTION public.withdraw_activity_for_users(
  p_left_id uuid, p_right_id uuid, p_reason text
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO public.activity_withdrawals (notification_id, user_id, reason)
  SELECT n.id, n.user_id, p_reason
  FROM public.notifications n
  WHERE n.kind IN (
    'user_followed', 'review_liked', 'comment_liked',
    'review_commented', 'comment_replied',
    'mentioned_in_review', 'mentioned_in_comment'
  ) AND ((n.user_id = p_left_id AND n.actor_id = p_right_id)
      OR (n.user_id = p_right_id AND n.actor_id = p_left_id))
  ON CONFLICT (notification_id) DO UPDATE
  SET reason = EXCLUDED.reason, withdrawn_at = now();
END;
$$;

CREATE OR REPLACE FUNCTION public.withdraw_deleted_actor_activity()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NEW.deleted IS TRUE AND OLD.deleted IS DISTINCT FROM TRUE THEN
    INSERT INTO public.activity_withdrawals (notification_id, user_id, reason)
    SELECT n.id, n.user_id, 'account_deleted'
    FROM public.notifications n
    WHERE n.actor_id = NEW.id
      AND n.kind IN (
        'user_followed', 'review_liked', 'comment_liked',
        'review_commented', 'comment_replied',
        'mentioned_in_review', 'mentioned_in_comment'
      )
    ON CONFLICT (notification_id) DO UPDATE
    SET reason = EXCLUDED.reason, withdrawn_at = now();
  END IF;
  RETURN NEW;
END;
$$;

COMMIT;
