-- Golden Glass is a current recognition projection, not an award history.
-- Regions and Google mappings are operator-owned; the client only receives
-- narrow, sanitized read interfaces.

BEGIN;

CREATE TABLE IF NOT EXISTS public.regions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  center_lat double precision NOT NULL CHECK (center_lat BETWEEN -90 AND 90),
  center_lon double precision NOT NULL CHECK (center_lon BETWEEN -180 AND 180),
  viewport_ne_lat double precision NOT NULL CHECK (viewport_ne_lat BETWEEN -90 AND 90),
  viewport_ne_lon double precision NOT NULL CHECK (viewport_ne_lon BETWEEN -180 AND 180),
  viewport_sw_lat double precision NOT NULL CHECK (viewport_sw_lat BETWEEN -90 AND 90),
  viewport_sw_lon double precision NOT NULL CHECK (viewport_sw_lon BETWEEN -180 AND 180),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.region_google_places (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region_id bigint NOT NULL REFERENCES public.regions(id) ON DELETE CASCADE,
  google_place_id text NOT NULL UNIQUE,
  google_label text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (region_id, google_place_id)
);

ALTER TABLE public.locations
  ADD COLUMN IF NOT EXISTS region_id bigint REFERENCES public.regions(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS neighborhood text,
  ADD COLUMN IF NOT EXISTS golden_glass_eligible boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS golden_glass_ineligibility_reason text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.locations'::regclass
      AND conname = 'locations_golden_glass_eligibility_check'
  ) THEN
    ALTER TABLE public.locations
      ADD CONSTRAINT locations_golden_glass_eligibility_check
      CHECK (
        (golden_glass_eligible AND golden_glass_ineligibility_reason IS NULL)
        OR
        (NOT golden_glass_eligible
          AND nullif(trim(golden_glass_ineligibility_reason), '') IS NOT NULL)
      );
  END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS locations_region_idx
  ON public.locations (region_id, id);

CREATE TABLE IF NOT EXISTS public.golden_glass_snapshot (
  region_id bigint NOT NULL REFERENCES public.regions(id) ON DELETE CASCADE,
  location_id bigint NOT NULL REFERENCES public.locations(id) ON DELETE CASCADE,
  rank smallint NOT NULL CHECK (rank BETWEEN 1 AND 5),
  raw_overall numeric(3, 1) NOT NULL CHECK (raw_overall BETWEEN 1 AND 5),
  adjusted_score numeric(8, 5) NOT NULL,
  distinct_reviewers integer NOT NULL CHECK (distinct_reviewers >= 3),
  latest_review_at timestamptz NOT NULL,
  refreshed_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (region_id, location_id),
  UNIQUE (region_id, rank)
);

CREATE INDEX IF NOT EXISTS golden_glass_snapshot_location_idx
  ON public.golden_glass_snapshot (location_id);

ALTER TABLE public.regions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.region_google_places ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.golden_glass_snapshot ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS regions_read_enabled ON public.regions;
CREATE POLICY regions_read_enabled ON public.regions
  FOR SELECT TO anon, authenticated
  USING (enabled = true);

DROP POLICY IF EXISTS region_google_places_read_enabled
  ON public.region_google_places;
CREATE POLICY region_google_places_read_enabled ON public.region_google_places
  FOR SELECT TO anon, authenticated
  USING (EXISTS (
    SELECT 1 FROM public.regions r
    WHERE r.id = region_google_places.region_id AND r.enabled = true
  ));

REVOKE ALL ON public.golden_glass_snapshot FROM anon, authenticated;
GRANT SELECT ON public.regions, public.region_google_places TO anon, authenticated;
GRANT ALL ON public.regions, public.region_google_places,
  public.golden_glass_snapshot TO service_role;

-- Rebuild the existing view with the current recognition flag. The flag is
-- exposed through a SECURITY DEFINER helper so raw snapshot rows stay private.
DROP FUNCTION IF EXISTS public.search_locations(text, integer);
DROP FUNCTION IF EXISTS public.search_locations(text, integer, integer);
DROP VIEW IF EXISTS public.location_ratings;

CREATE OR REPLACE FUNCTION public.is_golden_glass_location(p_location_id bigint)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.golden_glass_snapshot snapshot
    JOIN public.regions region ON region.id = snapshot.region_id
    JOIN public.locations location ON location.id = snapshot.location_id
    WHERE snapshot.location_id = p_location_id
      AND region.enabled = true
      AND location.golden_glass_eligible = true
  );
$$;

REVOKE ALL ON FUNCTION public.is_golden_glass_location(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_golden_glass_location(bigint)
  TO anon, authenticated, service_role;

CREATE VIEW public.location_ratings AS
SELECT
  l.id,
  l.name,
  l.address,
  l.neighborhood,
  l.region_id,
  gis.st_y((l.location)::gis.geometry) AS lat,
  gis.st_x((l.location)::gis.geometry) AS lon,
  COALESCE(round(avg(((r.taste + r.presentation) / 2.0)), 1), 0)::numeric AS rating,
  COALESCE(round(avg(r.taste), 1), 0)::numeric AS taste_avg,
  COALESCE(round(avg(r.presentation), 1), 0)::numeric AS presentation_avg,
  count(r.id)::integer AS total_ratings,
  public.is_golden_glass_location(l.id) AS is_golden_glass
FROM public.locations l
LEFT JOIN public.reviews r
  ON l.id = r.location AND r.state = 1
GROUP BY l.id, l.name, l.address, l.neighborhood, l.region_id, l.location;

ALTER VIEW public.location_ratings SET (security_invoker = on);
REVOKE ALL ON public.location_ratings FROM anon, authenticated;
GRANT SELECT ON public.location_ratings TO anon, authenticated, service_role;

-- Stable, visitor-readable region metadata. The Google mapping lookup is
-- intentionally a function so callers cannot enumerate disabled mappings.
CREATE OR REPLACE FUNCTION public.get_enabled_regions()
RETURNS TABLE (
  id bigint,
  slug text,
  name text,
  display_order integer,
  center_lat double precision,
  center_lon double precision,
  viewport_ne_lat double precision,
  viewport_ne_lon double precision,
  viewport_sw_lat double precision,
  viewport_sw_lon double precision
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT r.id, r.slug, r.name, r.display_order,
    r.center_lat, r.center_lon,
    r.viewport_ne_lat, r.viewport_ne_lon,
    r.viewport_sw_lat, r.viewport_sw_lon
  FROM public.regions r
  WHERE r.enabled = true
  ORDER BY r.display_order, r.name, r.id;
$$;

CREATE OR REPLACE FUNCTION public.resolve_region_for_google_place(p_place_id text)
RETURNS TABLE (
  id bigint,
  slug text,
  name text,
  display_order integer,
  center_lat double precision,
  center_lon double precision,
  viewport_ne_lat double precision,
  viewport_ne_lon double precision,
  viewport_sw_lat double precision,
  viewport_sw_lon double precision,
  google_place_id text,
  google_label text
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT r.id, r.slug, r.name, r.display_order,
    r.center_lat, r.center_lon,
    r.viewport_ne_lat, r.viewport_ne_lon,
    r.viewport_sw_lat, r.viewport_sw_lon,
    mapping.google_place_id, mapping.google_label
  FROM public.region_google_places mapping
  JOIN public.regions r ON r.id = mapping.region_id
  WHERE mapping.google_place_id = trim(p_place_id)
    AND r.enabled = true;
$$;

REVOKE ALL ON FUNCTION public.get_enabled_regions() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.resolve_region_for_google_place(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_enabled_regions()
  TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.resolve_region_for_google_place(text)
  TO anon, authenticated, service_role;

-- Map reads carry only the existing aggregate fields plus the current status.
-- Region membership comes from locations.region_id, never from a viewport.
CREATE OR REPLACE FUNCTION public.locations_in_region_view(
  p_min_lat double precision,
  p_min_long double precision,
  p_max_lat double precision,
  p_max_long double precision,
  p_region_id bigint
)
RETURNS TABLE (
  id bigint,
  name text,
  address text,
  lat double precision,
  long double precision,
  rating double precision,
  taste_avg double precision,
  presentation_avg double precision,
  total_ratings integer,
  is_golden_glass boolean
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, gis
AS $$
  SELECT l.id, l.name, l.address,
    gis.st_y(l.location::gis.geometry),
    gis.st_x(l.location::gis.geometry),
    round(avg((r.taste + r.presentation)::numeric / 2.0), 1)::double precision,
    round(avg(r.taste), 1)::double precision,
    round(avg(r.presentation), 1)::double precision,
    count(r.id)::integer,
    public.is_golden_glass_location(l.id)
  FROM public.locations l
  JOIN public.regions region ON region.id = l.region_id AND region.enabled = true
  JOIN public.reviews r ON r.location = l.id AND r.state = 1
  WHERE l.region_id = p_region_id
    AND gis.st_intersects(
      l.location,
      gis.st_makeenvelope(
        p_min_long, p_min_lat, p_max_long, p_max_lat, 4326
      )::gis.geography
    )
  GROUP BY l.id, l.name, l.address, l.location;
$$;

CREATE OR REPLACE FUNCTION public.public_locations_in_region_view(
  p_min_lat double precision,
  p_min_long double precision,
  p_max_lat double precision,
  p_max_long double precision,
  p_region_id bigint
)
RETURNS TABLE (
  id bigint,
  name text,
  address text,
  lat double precision,
  long double precision,
  rating double precision,
  taste_avg double precision,
  presentation_avg double precision,
  total_ratings integer,
  is_golden_glass boolean
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, gis, pg_temp
AS $$
  SELECT l.id, l.name, l.address,
    gis.st_y(l.location::gis.geometry),
    gis.st_x(l.location::gis.geometry),
    round(avg((r.taste + r.presentation)::numeric / 2.0), 1)::double precision,
    round(avg(r.taste), 1)::double precision,
    round(avg(r.presentation), 1)::double precision,
    count(r.id)::integer,
    public.is_golden_glass_location(l.id)
  FROM public.locations l
  JOIN public.regions region ON region.id = l.region_id AND region.enabled = true
  JOIN public.reviews r ON r.location = l.id AND r.state = 1
  JOIN public.profiles p ON p.id = r.user_id AND p.deleted = false AND p.is_public = true
  WHERE l.region_id = p_region_id
    AND gis.st_intersects(
      l.location,
      gis.st_makeenvelope(
        p_min_long, p_min_lat, p_max_long, p_max_lat, 4326
      )::gis.geography
    )
  GROUP BY l.id, l.name, l.address, l.location;
$$;

REVOKE ALL ON FUNCTION public.locations_in_region_view(double precision, double precision, double precision, double precision, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.public_locations_in_region_view(double precision, double precision, double precision, double precision, bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.locations_in_region_view(double precision, double precision, double precision, double precision, bigint)
  TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.public_locations_in_region_view(double precision, double precision, double precision, double precision, bigint)
  TO anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION public.get_region_members_v1(
  p_region_id bigint,
  p_search text DEFAULT NULL,
  p_limit integer DEFAULT 50
)
RETURNS TABLE (
  id uuid,
  username text,
  avatar_url text,
  is_verified boolean,
  follower_count integer,
  review_count bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT p.id, p.username, p.avatar_url, p.is_verified,
    p.follower_count,
    count(r.id)::bigint AS review_count
  FROM public.profiles p
  JOIN public.reviews r ON r.user_id = p.id AND r.state = 1
  JOIN public.locations l ON l.id = r.location AND l.region_id = p_region_id
  JOIN public.regions region ON region.id = l.region_id AND region.enabled = true
  WHERE auth.uid() IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.profiles viewer
      WHERE viewer.id = auth.uid() AND viewer.deleted = false
    )
    AND p.deleted = false
    AND p.username IS NOT NULL
    AND public.is_member_visible(p.id)
    AND (
      nullif(trim(p_search), '') IS NULL
      OR p.username ILIKE '%' || replace(replace(trim(p_search), '%', '\\%'), '_', '\\_') || '%'
    )
  GROUP BY p.id, p.username, p.avatar_url, p.is_verified, p.follower_count
  ORDER BY count(r.id) DESC, p.username, p.id
  LIMIT greatest(1, least(coalesce(p_limit, 50), 50));
$$;

REVOKE ALL ON FUNCTION public.get_region_members_v1(bigint, text, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_region_members_v1(bigint, text, integer)
  TO authenticated, service_role;

-- Current five-recipient calculation. Each member contributes one average per
-- location. DELETE + INSERT is one transaction, so readers see the previous
-- complete snapshot until the replacement commits.
CREATE OR REPLACE FUNCTION public.refresh_golden_glass_v1()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF COALESCE(auth.role(), '') NOT IN ('', 'service_role')
     AND current_user <> 'postgres' THEN
    RAISE EXCEPTION 'Golden Glass refresh is service-role only'
      USING ERRCODE = '42501';
  END IF;

  DELETE FROM public.golden_glass_snapshot WHERE true;

  INSERT INTO public.golden_glass_snapshot (
    region_id, location_id, rank, raw_overall, adjusted_score,
    distinct_reviewers, latest_review_at, refreshed_at
  )
  WITH member_contributions AS (
    SELECT l.region_id, l.id AS location_id, r.user_id,
      avg((r.taste + r.presentation) / 2.0)::numeric AS member_overall,
      max(r.inserted_at) AS latest_review_at
    FROM public.locations l
    JOIN public.regions region
      ON region.id = l.region_id AND region.enabled = true
    JOIN public.reviews r ON r.location = l.id AND r.state = 1
    JOIN public.profiles p ON p.id = r.user_id AND p.deleted = false
    WHERE l.golden_glass_eligible = true
    GROUP BY l.region_id, l.id, r.user_id
  ),
  region_stats AS (
    SELECT region_id, avg(member_overall) AS region_c
    FROM member_contributions
    GROUP BY region_id
  ),
  global_stats AS (
    SELECT avg(all_contributions.member_overall) AS global_c
    FROM (
      SELECT r.location, r.user_id,
        avg((r.taste + r.presentation) / 2.0)::numeric AS member_overall
      FROM public.reviews r
      JOIN public.locations l ON l.id = r.location
      JOIN public.profiles p ON p.id = r.user_id AND p.deleted = false
      WHERE r.state = 1
      GROUP BY r.location, r.user_id
    ) all_contributions
  ),
  candidates AS (
    SELECT contributions.region_id, contributions.location_id,
      avg(contributions.member_overall)::numeric AS raw_overall,
      count(*)::integer AS distinct_reviewers,
      max(contributions.latest_review_at) AS latest_review_at
    FROM member_contributions contributions
    GROUP BY contributions.region_id, contributions.location_id
    HAVING count(*) >= 3
  ),
  scored AS (
    SELECT candidates.*,
      (
        (candidates.distinct_reviewers::numeric /
          (candidates.distinct_reviewers + 3)) * candidates.raw_overall
        + (3::numeric /
          (candidates.distinct_reviewers + 3)) *
          coalesce(region_stats.region_c, global_stats.global_c, 3)
      ) AS adjusted_score
    FROM candidates
    LEFT JOIN region_stats ON region_stats.region_id = candidates.region_id
    CROSS JOIN global_stats
  ),
  ordered AS (
    SELECT scored.*,
      row_number() OVER (
        PARTITION BY scored.region_id
        ORDER BY scored.adjusted_score DESC,
          scored.distinct_reviewers DESC,
          scored.raw_overall DESC,
          scored.latest_review_at DESC,
          scored.location_id ASC
      ) AS calculated_rank
    FROM scored
  )
  SELECT ordered.region_id, ordered.location_id,
    ordered.calculated_rank::smallint,
    round(ordered.raw_overall, 1), ordered.adjusted_score,
    ordered.distinct_reviewers, ordered.latest_review_at, now()
  FROM ordered
  WHERE ordered.calculated_rank <= 5;
END;
$$;

REVOKE ALL ON FUNCTION public.refresh_golden_glass_v1() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.refresh_golden_glass_v1() TO service_role;

CREATE OR REPLACE FUNCTION public.get_golden_glass_inspection_v1(
  p_region_id bigint DEFAULT NULL
)
RETURNS TABLE (
  region_id bigint,
  location_id bigint,
  calculated_rank bigint,
  is_current boolean,
  venue_name text,
  raw_overall numeric,
  adjusted_score numeric,
  distinct_reviewers integer,
  latest_review_at timestamptz,
  eligible boolean,
  ineligibility_reason text,
  refreshed_at timestamptz
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF COALESCE(auth.role(), '') NOT IN ('', 'service_role')
     AND current_user <> 'postgres' THEN
    RAISE EXCEPTION 'Golden Glass inspection is service-role only'
      USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  WITH member_contributions AS (
    SELECT l.region_id, l.id AS location_id, r.user_id,
      avg((r.taste + r.presentation) / 2.0)::numeric AS member_overall,
      max(r.inserted_at) AS latest_review_at
    FROM public.locations l
    JOIN public.regions region
      ON region.id = l.region_id AND region.enabled = true
    JOIN public.reviews r ON r.location = l.id AND r.state = 1
    JOIN public.profiles p ON p.id = r.user_id AND p.deleted = false
    WHERE l.golden_glass_eligible = true
      AND (p_region_id IS NULL OR l.region_id = p_region_id)
    GROUP BY l.region_id, l.id, r.user_id
  ),
  region_stats AS (
    SELECT member_contributions.region_id, avg(member_overall) AS region_c
    FROM member_contributions
    GROUP BY member_contributions.region_id
  ),
  global_stats AS (
    SELECT avg(all_contributions.member_overall) AS global_c
    FROM (
      SELECT r.location, r.user_id,
        avg((r.taste + r.presentation) / 2.0)::numeric AS member_overall
      FROM public.reviews r
      JOIN public.locations l ON l.id = r.location
      JOIN public.profiles p ON p.id = r.user_id AND p.deleted = false
      WHERE r.state = 1
      GROUP BY r.location, r.user_id
    ) all_contributions
  ),
  candidates AS (
    SELECT contributions.region_id, contributions.location_id,
      avg(contributions.member_overall)::numeric AS raw_overall,
      count(*)::integer AS distinct_reviewers,
      max(contributions.latest_review_at) AS latest_review_at
    FROM member_contributions contributions
    GROUP BY contributions.region_id, contributions.location_id
    HAVING count(*) >= 3
  ),
  scored AS (
    SELECT candidates.*,
      (candidates.distinct_reviewers::numeric /
        (candidates.distinct_reviewers + 3)) * candidates.raw_overall
      + (3::numeric / (candidates.distinct_reviewers + 3))
        * coalesce(region_stats.region_c, global_stats.global_c, 3)
        AS adjusted_score
    FROM candidates
    LEFT JOIN region_stats ON region_stats.region_id = candidates.region_id
    CROSS JOIN global_stats
  ),
  ordered AS (
    SELECT scored.*,
      row_number() OVER (
        PARTITION BY scored.region_id
        ORDER BY scored.adjusted_score DESC,
          scored.distinct_reviewers DESC,
          scored.raw_overall DESC,
          scored.latest_review_at DESC,
          scored.location_id ASC
      ) AS calculated_rank
    FROM scored
  ),
  refreshes AS (
    SELECT snapshot.region_id, max(snapshot.refreshed_at) AS refreshed_at
    FROM public.golden_glass_snapshot snapshot
    GROUP BY snapshot.region_id
  )
  SELECT ordered.region_id, ordered.location_id, ordered.calculated_rank,
    ordered.calculated_rank <= 5, location.name,
    round(ordered.raw_overall, 1), ordered.adjusted_score,
    ordered.distinct_reviewers, ordered.latest_review_at,
    location.golden_glass_eligible,
    location.golden_glass_ineligibility_reason,
    refreshes.refreshed_at
  FROM ordered
  JOIN public.locations location ON location.id = ordered.location_id
  LEFT JOIN refreshes ON refreshes.region_id = ordered.region_id
  ORDER BY ordered.region_id, ordered.calculated_rank;
END;
$$;

REVOKE ALL ON FUNCTION public.get_golden_glass_inspection_v1(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_golden_glass_inspection_v1(bigint)
  TO service_role;

CREATE OR REPLACE FUNCTION public.get_golden_glass_v1(p_region_id bigint)
RETURNS TABLE (
  region_id bigint,
  location_id bigint,
  venue_name text,
  address text,
  neighborhood text,
  raw_overall numeric,
  distinct_reviewers integer,
  latest_review_at timestamptz,
  refreshed_at timestamptz,
  latest_review_image_url text,
  is_golden_glass boolean
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT snapshot.region_id, snapshot.location_id, location.name,
    location.address, location.neighborhood, snapshot.raw_overall,
    snapshot.distinct_reviewers, snapshot.latest_review_at,
    snapshot.refreshed_at, latest_review.image_url,
    true
  FROM public.golden_glass_snapshot snapshot
  JOIN public.regions region
    ON region.id = snapshot.region_id AND region.enabled = true
  JOIN public.locations location ON location.id = snapshot.location_id
  LEFT JOIN LATERAL (
    SELECT review.image_url
    FROM public.reviews review
    JOIN public.profiles reviewer
      ON reviewer.id = review.user_id AND reviewer.deleted = false
    WHERE review.location = location.id AND review.state = 1
    ORDER BY review.inserted_at DESC, review.id DESC
    LIMIT 1
  ) latest_review ON true
  WHERE auth.uid() IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.profiles viewer
      WHERE viewer.id = auth.uid() AND viewer.deleted = false
    )
    AND snapshot.region_id = p_region_id
  ORDER BY snapshot.rank;
$$;

REVOKE ALL ON FUNCTION public.get_golden_glass_v1(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_golden_glass_v1(bigint)
  TO authenticated, service_role;

-- Six initial canonical regions. Google IDs are intentionally absent until an
-- operator verifies them through Places (New) and creates the mapping.
INSERT INTO public.regions (
  slug, name, enabled, display_order,
  center_lat, center_lon,
  viewport_ne_lat, viewport_ne_lon, viewport_sw_lat, viewport_sw_lon
)
VALUES
  ('vancouver', 'Vancouver', true, 10, 49.2827, -123.1207, 49.42, -122.95, 49.17, -123.30),
  ('seattle', 'Seattle', true, 20, 47.6062, -122.3321, 47.75, -122.15, 47.48, -122.55),
  ('los-angeles', 'Los Angeles', true, 30, 34.0522, -118.2437, 34.30, -117.95, 33.85, -118.55),
  ('new-york', 'New York', true, 40, 40.7128, -74.0060, 40.95, -73.70, 40.48, -74.30),
  ('paris', 'Paris', true, 50, 48.8566, 2.3522, 49.00, 2.60, 48.70, 2.05),
  ('bangkok', 'Bangkok', true, 60, 13.7563, 100.5018, 14.00, 100.75, 13.50, 100.25)
ON CONFLICT (slug) DO UPDATE SET
  name = excluded.name,
  display_order = excluded.display_order,
  updated_at = now();

-- Supabase projects that enable pg_cron get a daily refresh automatically.
-- Projects without it can invoke the same service-role function from their
-- deployment scheduler; keeping this optional makes local migrations portable.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    BEGIN
      EXECUTE $job$
        SELECT cron.schedule(
          'golden-glass-daily-refresh',
          '15 8 * * *',
          'SELECT public.refresh_golden_glass_v1()'
        )
      $job$;
    EXCEPTION WHEN unique_violation THEN
      NULL;
    END;
  END IF;
END;
$$;

-- Recreate the legacy search RPCs before this migration commits. The view
-- rebuild above temporarily removes functions that return its row type, so
-- older clients must not observe a committed schema without search.
CREATE OR REPLACE FUNCTION public.search_locations(
  p_query text,
  p_limit integer DEFAULT 20
)
RETURNS SETOF public.location_ratings
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT lr.*
  FROM public.location_ratings lr
  WHERE p_query IS NOT NULL
    AND length(trim(p_query)) >= 2
    AND (
      lr.name ILIKE '%' || trim(p_query) || '%'
      OR lr.address ILIKE '%' || trim(p_query) || '%'
      OR similarity(lr.name, trim(p_query)) > 0.25
    )
  ORDER BY
    (lr.name ILIKE '%' || trim(p_query) || '%') DESC,
    GREATEST(
      similarity(lr.name, trim(p_query)),
      similarity(COALESCE(lr.address, ''), trim(p_query))
    ) DESC,
    lr.total_ratings DESC,
    lr.id ASC
  LIMIT greatest(1, least(COALESCE(p_limit, 20), 50));
$$;

CREATE OR REPLACE FUNCTION public.search_locations(
  p_query text,
  p_limit integer,
  p_offset integer
)
RETURNS SETOF public.location_ratings
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT lr.*
  FROM public.location_ratings lr
  WHERE p_query IS NOT NULL
    AND length(trim(p_query)) >= 2
    AND (
      lr.name ILIKE '%' || trim(p_query) || '%'
      OR lr.address ILIKE '%' || trim(p_query) || '%'
      OR similarity(lr.name, trim(p_query)) > 0.25
    )
  ORDER BY
    (lr.name ILIKE '%' || trim(p_query) || '%') DESC,
    GREATEST(
      similarity(lr.name, trim(p_query)),
      similarity(COALESCE(lr.address, ''), trim(p_query))
    ) DESC,
    lr.total_ratings DESC,
    lr.id ASC
  LIMIT greatest(1, least(COALESCE(p_limit, 20), 50))
  OFFSET greatest(COALESCE(p_offset, 0), 0);
$$;

REVOKE ALL ON FUNCTION public.search_locations(text, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.search_locations(text, integer, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.search_locations(text, integer)
  TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.search_locations(text, integer, integer)
  TO anon, authenticated, service_role;

COMMIT;
